### ISSUE TITLE
Added to [main]

### ISSUE THREAD

**Issue by demmm** [KaOS-Community-Packages/mpv-zsh#1]
To prepare for new options in smplayer, mpv is added to the repo.
Version in main uses lua, so if you prefer to keep a lua free version, rename mpv in KCP, otherwise, it will need to be removed.

**Comment by Adurol** [comment]
As it seems like there are still users who maintain and use this zsh-enabled mpv-build, I will close this issue.
Please reopen it or create a new issue should new circumstances arise.

**Comment by demmm** [comment]
MPV in main has zsh support added (no need to build with zsh installed), this version will now be removed.
